apiVersion: batch/v1
kind: Job
metadata:
  name: batch-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: main
        image: luksa/batch-job
      restartPolicy: OnFailure
